from __future__ import unicode_literals

API_URL = 'https://api.tvmaze.com'
search_show_name = 'https://api.tvmaze.com/search/shows?'
search_show_best_match = 'https://api.tvmaze.com/singlesearch/shows?'
search_external_show_id = 'https://api.tvmaze.com/lookup/shows?'
show_information = 'https://api.tvmaze.com/shows/{0}'
show_episode_list = 'https://api.tvmaze.com/shows/{0}/episodes?'
show_episode = 'http://api.tvmaze.com/shows/{0}/episodebynumber?'
show_episodes_on_date = 'http://api.tvmaze.com/shows/{0}/episodesbydate?'
show_season_list = 'http://api.tvmaze.com/shows/{0}/seasons'
season_episode_list = 'http://api.tvmaze.com/seasons/{0}/episodes'
show_alias_list = 'http://api.tvmaze.com/shows/{0}/akas'
episode_information = 'http://api.tvmaze.com/episodes/{0}?'
show_cast = 'http://api.tvmaze.com/shows/{0}/cast'
show_crew = 'http://api.tvmaze.com/shows/{0}/crew'
