API_URL = 'https://api.tvmaze.com'
search_show_name = 'https://api.tvmaze.com/search/shows?'
single_search_show_name = 'https://api.tvmaze.com/singlesearch/shows?'
search_external_show_id = 'https://api.tvmaze.com/lookup/shows?'
show_information = 'https://api.tvmaze.com/shows/{0}'
show_episode_list = 'https://api.tvmaze.com/shows/{0}/episodes?'
show_episode = 'http://api.tvmaze.com/shows/{0}/episodebynumber?'
