API_URL = 'https://api.tvmaze.com'
search_show_name = f'{API_URL}/search/shows?'
single_search_show_name = f'{API_URL}/singlesearch/shows?'
search_external_show_id = f'{API_URL}/lookup/shows?'
search_tvmaze_id = f'{API_URL}/shows/'
